### ISSUE TITLE
Strava source plugin

### ISSUE THREAD

**Issue by fyrkant** [danoc/danoc.me#2]
Hey!
Really cool with the strava source plugin, I've been looking for exactly this! Is there anything I can do to help to open source it and get it on npm?

**Comment by danoc** [comment]
Hi! Thanks for reaching out, @fyrkant!

I've improved the plugin a bit this morning, making it more configurable:
https://github.com/danoc/danoc.me/commit/87fc8bddd42e924cd5bab285f0572f322b6b9e03

I'll move it into a separate repo and publish on NPM in a few hours.

**Comment by fyrkant** [comment]
Yay! Then I can start hacking on adding some runs to my own site tonight. 🤓

**Comment by danoc** [comment]
Hey @fyrkant – Sorry for the delay. Just created it here:
https://github.com/danoc/gatsby-source-strava-activities

Happy to accept contributions if you have any improvements or suggestions. 😄

**Comment by danoc** [comment]
Also, let me know when you have something up on your site so I can see it!
